spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    host: "localhost"
    lettuce:
      pool:
        max-active: 5
        max-idle: 5
management:
  endpoints:
    web:
      exposure:
        include: "*"
