
mybatis:
  mapper-locations: 'classpath*:/mapper/**/*.xml'
  type-aliases-package: 'zgpeace.spring.mybatis.model'
  type-handlers-package: 'zgpeace.spring.mybatis.handler'
  configuration:
    map-underscore-to-camel-case: true