spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_example
    username: springuser
    password: ThePassword

  jpa:
    hibernate:
      ddl-auto: create  # 第一次简表create  后面用update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect