spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cache:
    type: redis
    cache-names: "coffee"
    redis:
      time-to-live: 5000
      cache-null-values: false
  redis:
    host: localhost
management:
  endpoints:
    web:
      exposure:
        include: "*"
